# Generated by Django 4.2 on 2023-04-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position', '0001_initial'),
        ('specialization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('third_name', models.CharField(max_length=255)),
                ('j_b', models.FileField(upload_to='J_D')),
                ('job', models.TextField(max_length=511)),
                ('depat_name', models.CharField(max_length=511)),
                ('center_name', models.CharField(max_length=511)),
                ('group_name', models.CharField(max_length=511)),
                ('position', models.ManyToManyField(to='position.position')),
                ('specialization', models.ManyToManyField(to='specialization.specialization')),
            ],
        ),
    ]
