# Generated by Django 4.2 on 2023-04-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('third_name', models.CharField(max_length=255)),
                ('depat_name', models.CharField(max_length=511)),
                ('center_name', models.CharField(max_length=511)),
                ('group_name', models.CharField(max_length=511)),
                ('pos_name', models.CharField(max_length=511)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('id_emp', models.ManyToManyField(to='employee.employee')),
            ],
        ),
    ]
